# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.11.0.tar.gz";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9Ys0pAABixEvvQvhVXAdqRE3wrZk_wiL9TPNHhB8d";
    path = fetchzip {
      url = "https://github.com/ziglibs/ini/archive/918f16d0dcf893d0c1cdffe204faa08bb3584e04.tar.gz";
      hash = "sha256-4o4tFV05IV/uSQWDtwqaeStY46ORmze//2IlBQ5MhnY=";
    };
  }
  {
    name = "zig_pam-0.1.0--cHVhttYAAAZqSMtkuDM1YHlw7VVCtgmMsz5lSg9B8ez";
    path = fetchgit {
      url = "https://github.com/ashametrine/zig-pam";
      rev = "8b547dbc87e8cb959440d98bc39e7792cbf65015";
      hash = "sha256-Jqe58DslIQVgO7fNlqzRtOWQstK7/SEohrxHcUdH+O8=";
    };
  }
  {
    name = "zigini-0.4.0-BSkB7eJUAAD0Nt14fV482O8qNxsW8h_6BCTUIulluojv";
    path = fetchgit {
      url = "https://github.com/ashametrine/zigini";
      rev = "fe98c40f646aada9e68fcc955180929628cad3f6";
      hash = "sha256-PGu5//rxAYvbz8DUjyix9WeJxAQmDtwlSiifbCtqhh8=";
    };
  }
]
