# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "clap-0.11.0-oBajB7foAQC3Iyn4IVCkUdYaOVVng5IZkSncySTjNig1";
    path = fetchgit {
      url = "https://github.com/Hejsil/zig-clap";
      rev = "fc1e5cc3f6d9d3001112385ee6256d694e959d2f";
      hash = "sha256-sIDCZW4q9BQwy4AJjJ6r+mSkJ3usbnMmY9zkE4EVAy8=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9YiwsAACghqF8LZyjAF2H_NnL6n29QLuCe0fsmPTo";
    path = fetchgit {
      url = "https://github.com/AshAmetrine/ziglibs-ini";
      branchName = "zig-0.16.0";
      rev = "3b733e10adc6c4c48050709b97a22258bc2e6156";
      hash = "sha256-t+6zFMwpPgMrUygBcQCM0s10zK320D46xAgr2FSw3tU=";
    };
  }
  {
    name = "zig_pam-0.1.0--cHVhttYAAAZqSMtkuDM1YHlw7VVCtgmMsz5lSg9B8ez";
    path = fetchgit {
      url = "https://github.com/ashametrine/zig-pam";
      rev = "8b547dbc87e8cb959440d98bc39e7792cbf65015";
      hash = "sha256-Jqe58DslIQVgO7fNlqzRtOWQstK7/SEohrxHcUdH+O8=";
    };
  }
  {
    name = "zigini-0.5.0-BSkB7e9WAACfyCBABNZiWL3gFMw18GKn3qBcPs8L1Ec1";
    path = fetchgit {
      url = "https://github.com/AshAmetrine/zigini";
      rev = "a665d081dda42664a96da2840ea09c5ccf9d0692";
      hash = "sha256-8zwniFOQFTrFNOrfudhtoCXQBTBKSmc3XF1bNSb3Av8=";
    };
  }
]
