# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "clap-0.11.0-oBajB-HnAQDPCKYzwF7rO3qDFwRcD39Q0DALlTSz5H7e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.11.0.tar.gz";
      hash = "sha256-XytqwtoE0xaR43YustgK68sAQPVfC0Dt+uCs8UTfkbU=";
    };
  }
  {
    name = "ini-0.1.0-YCQ9Ys0pAABixEvvQvhVXAdqRE3wrZk_wiL9TPNHhB8d";
    path = fetchzip {
      url = "https://github.com/ziglibs/ini/archive/918f16d0dcf893d0c1cdffe204faa08bb3584e04.tar.gz";
      hash = "sha256-4o4tFV05IV/uSQWDtwqaeStY46ORmze//2IlBQ5MhnY=";
    };
  }
  {
    name = "zig_pam-0.1.0--cHVhklUAADuOUdOED_5O2TSKx69IK1HHRkmJSWZ5AiN";
    path = fetchgit {
      url = "https://github.com/Kawaii-Ash/zig-pam";
      rev = "3fd2f13cd8fec0297f46cc31589418271b90acdd";
      hash = "sha256-JydVPyWaKWp6/lX61TkEQy//rLsKComyXJY0s0XupKA=";
    };
  }
  {
    name = "zigini-0.3.2-BSkB7UVDAAAErcEC6s7zF9bKTe7CjdBgrV35K3DGHpbr";
    path = fetchgit {
      url = "https://github.com/Kawaii-Ash/zigini";
      rev = "831f6aff55703b7fa34b43c972d60eb3d5d6f4a4";
      hash = "sha256-5Q4WSsWUaeVCsDgb8mBAf6ufwg6sGDlL1U0jMESgmDo=";
    };
  }
]
