# PAM service name
service_name = login

# The user the greeter is run as
greeter_user = greeter

# Target VT to run the greeter/session.
# This can be left blank and the current controlling tty will be used.
vt =

# greeter command with optional args
# example: /bin/zgsld-agetty-greeter 
greeter_cmd =

# Only when built with x11_support
[x11]
# X Server command 
# - does not accept args
cmd = /bin/X
