# PAM service name for starting a user session
service_name = login

# The user the greeter is run as
greeter_user = greeter

# PAM service for starting a greeter session
greeter_service_name =

# Target VT to run the greeter/session.
# This can be left blank and the current controlling tty will be used.
vt =

# greeter command with optional args
# example: /bin/zgsld-agetty-greeter 
greeter_cmd =

# Only when built with x11 support (-Dx11)
[x11]
# X Server command 
# - does not accept args
cmd = /bin/X
